//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cw.Ultracem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBancoSiesa
    {
        public long Id { get; set; }
        public string TipoConsulta { get; set; }
        public string XmlBanco { get; set; }
        public string XmlSiesa { get; set; }
        public string Resultado { get; set; }
        public Nullable<System.DateTime> FechaConsumo { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string Referencia1 { get; set; }
        public string Referencia2 { get; set; }
        public Nullable<decimal> TotalTransaccion { get; set; }
        public Nullable<decimal> IdBanco { get; set; }
    
        public virtual BancosWS BancosWS { get; set; }
    }
}
